name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: '1.10.1.763'

      - name: Build tests
        working-directory: ./backend
        run: clojure -M:test

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - run: npm install karma karma-cljs-test --save-dev karma-chrome-launcher --save-dev
        working-directory: ./frontend

      - run: npm install -g karma-cli

      - name: Build tests
        working-directory: ./frontend
        run: npx shadow-cljs compile ci

      - name: Run tests
        working-directory: ./frontend
        run: karma start --single-run
